### ISSUE TITLE
[Bug]: Duplication Glitch With Upgrades Being Applied In-World (Neoforge)

### ISSUE THREAD

**Issue by ThatElektrika** [Qelifern/IronFurnacesNeoForge#1]
This video should sum it up.

https://github.com/Qelifern/IronFurnacesNeoForge/assets/74426302/1bddb2cb-06a2-45be-87e8-7b44cf84f0b0

**Comment by Qelifern** [comment]
Thanks for reporting.
Will look at this on monday.

**Comment by Qelifern** [comment]
4.2.4 fixes this
