### ISSUE TITLE
Copy paste tool does not work with the side configs correctly

### ISSUE THREAD

**Issue by VoidTest** [Qelifern/IronFurnacesNeoForge#5]
If the back is set to input or anything on a side of the furnace and copied and pasted to a furnace in a different orientation it will not have the setting on the same side. The side configs save to the compass orientation and are not based on the furnaces orientation.

This happened on ATM 10-0.7

**Comment by Qelifern** [comment]
4.2.5 now copies over the horizontal facing aswell

in future I might make it so the side configs adjust to the current facing of the block you are copying to
